package dev.bauxe.konaste.models.scores

import dev.bauxe.konaste.models.UnknownField
import dev.bauxe.konaste.models.songs.ChartDifficulty
import dev.bauxe.konaste.utils.ByteArrayReader
import kotlinx.serialization.Serializable

@Serializable
data class ResultScreenData(
    val long0: UnknownField,
    val long1: UnknownField,
    val long2: UnknownField,
    val long3: UnknownField,
    val long4: UnknownField,
    val long5: UnknownField,
    val long6: UnknownField,
    val long7: UnknownField,
    val long8: UnknownField,
    val long9: UnknownField,
    val long10: UnknownField,
    val long11: UnknownField,
    val long12: UnknownField,
    val long13: UnknownField,
    val long14: UnknownField,
    val long15: UnknownField,
    val songId: Int,
    val unknown1: Int,
    val score: Int,
    val bestScore: Int,
    val combo: Int, // 2e
    val criticals: Int,
    val nears: Int,
    val misses: Int,
    val health: Int,
    val level: Int,
    val difficulty: Int,
    val grade: Int,
    val bestGrade: Int,
    val int0: UnknownField,
    val clearMark: Int,
    val bestClearMark: Int,
    val int1: UnknownField,
    val long19: UnknownField,
    val int2: UnknownField,
    val ex: Int,
    val bestEx: Int,
    val errorEarly: Int,
    val nearEarly: Int,
    val criticalEarly: Int,
    val sCritical: Int,
    val criticalLate: Int,
    val nearLate: Int,
    val errorLate: Int,
    val sCriticalChip: Int,
    val criticalChip: Int,
    val nearChip: Int,
    val errorChip: Int,
    val sCriticalLong: Int,
    val missLong: Int,
    val sCriticalTsumami: Int,
    val missTsumami: Int,
    val int3: UnknownField,
    val long20: UnknownField,
    val long21: UnknownField,
    val long22: UnknownField,
    val long23: UnknownField,
    val long24: UnknownField,
    val long25: UnknownField,
    val long26: UnknownField,
    val long27: UnknownField,
    val long28: UnknownField,
    val long29: UnknownField,
    val long30: UnknownField,
    val long31: UnknownField,
    val long32: UnknownField,
    val long33: UnknownField,
    val long34: UnknownField,
    val long35: UnknownField,
    val long36: UnknownField,
    val long37: UnknownField,
    val long38: UnknownField,
    val long39: UnknownField,
    val long40: UnknownField,
    val long41: UnknownField,
    val long42: UnknownField,
    val long43: UnknownField,
    val long44: UnknownField,
    val long45: UnknownField,
    val long46: UnknownField,
    val long47: UnknownField,
    val long48: UnknownField,
    val long49: UnknownField,
    val long50: UnknownField,
    val long51: UnknownField,
    val long52: UnknownField,
    val long53: UnknownField,
    val long54: UnknownField,
    val long55: UnknownField,
    val long56: UnknownField,
    val long57: UnknownField,
    val long58: UnknownField,
    val long59: UnknownField,
    val long60: UnknownField,
    val long61: UnknownField,
    val long62: UnknownField,
    val long63: UnknownField,
    val long64: UnknownField,
    val long65: UnknownField,
    val long66: UnknownField,
    val long67: UnknownField,
    val long68: UnknownField,
) {
  companion object {
    const val SIZE = 672

    fun fromByteReader(reader: ByteArrayReader): ResultScreenData {
      return ResultScreenData(
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextUnknownInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextUnknownInt(),
          reader.nextUnknownLong(),
          reader.nextUnknownInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextInt(),
          reader.nextUnknownInt(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong(),
          reader.nextUnknownLong())
    }
  }
}

@Serializable
data class ResultScreen(
    val songName: String,
    val artist: String,
    val difficulty: ChartDifficulty,
    val level: Int,
    val score: Int,
    val exScore: Int,
    val combo: Int,
    val bestScore: Int,
    val bestExScore: Int,
    val maxEx: Int,
    val clearMark: String,
    val bestClearMark: String,
    val grade: String,
    val bestGrade: String,
    val imagePath: String,
)
